CREATE SEQUENCE client_id_seq;
CREATE TABLE CLIENT (
ID smallint PRIMARY KEY DEFAULT nextval('client_id_seq') ,
Nom VARCHAR NOT NULL,
Prenom VARCHAR NOT NULL,
DateDeNaissance DATE NOT NULL,
Adresse VARCHAR,
NumeroTel VARCHAR
);
ALTER SEQUENCE client_id_seq OWNED BY CLIENT.ID;

CREATE SEQUENCE personnel_id_seq;
CREATE TABLE PERSONNEL (
ID smallint PRIMARY KEY DEFAULT nextval('personnel_id_seq') ,
Nom VARCHAR NOT NULL,
Prenom VARCHAR NOT NULL,
DateDeNaissance DATE,
Adresse VARCHAR,
NumeroTel VARCHAR,
Poste VARCHAR CHECK (Poste IN ('Veto', 'Assistant')),
Specialites JSON
) ;
ALTER SEQUENCE personnel_id_seq OWNED BY PERSONNEL.ID;

CREATE TABLE ESPECE (
Espece VARCHAR PRIMARY KEY
) ;

CREATE SEQUENCE patient_id_seq;
CREATE TABLE PATIENT (
ID smallint PRIMARY KEY DEFAULT nextval('patient_id_seq') ,
Nom VARCHAR NOT NULL,
DateDeNaissance DATE NOT NULL,
Taille VARCHAR CHECK (Taille IN ('Petite', 'Moyenne')),
NumeroPuceID VARCHAR,
NumeroPasseport VARCHAR,
Espece VARCHAR,
FOREIGN KEY (Espece) REFERENCES ESPECE(espece)
) ;
ALTER SEQUENCE patient_id_seq OWNED BY PATIENT.ID;

CREATE TABLE MEDICAMENT (
NomMolecule VARCHAR PRIMARY KEY,
Description VARCHAR,
InterditPour JSON
) ;

CREATE SEQUENCE mesure_id_seq;
CREATE TABLE MESURE (
ID smallint PRIMARY KEY DEFAULT nextval('mesure_id_seq') ,
IDPatient INTEGER NOT NULL,
DateEtHeure TIMESTAMP,
Taille REAL,
Poids REAL ,
CONSTRAINT CHK_TaillePoids CHECK (Taille IS NOT NULL OR Poids IS NOT NULL),
FOREIGN KEY (IDPatient) REFERENCES PATIENT(ID)
) ;
ALTER SEQUENCE mesure_id_seq OWNED BY MESURE.ID;

CREATE SEQUENCE traitement_id_seq;
CREATE TABLE TRAITEMENT (
ID smallint PRIMARY KEY DEFAULT nextval('traitement_id_seq') ,
IDPatient INTEGER NOT NULL,
DateEtHeure TIMESTAMP ,
DateDebut DATE ,
Duree INTEGER,
 FOREIGN KEY (IDPatient) REFERENCES PATIENT(ID)
) ;
ALTER SEQUENCE traitement_id_seq OWNED BY TRAITEMENT.ID;

CREATE SEQUENCE resultat_analyse_id_seq;
CREATE TABLE RESULTAT_ANALYSE (
ID smallint PRIMARY KEY DEFAULT nextval('resultat_analyse_id_seq') ,
IDPatient INTEGER NOT NULL,
DateEtHeure TIMESTAMP,
Resultat VARCHAR,
FOREIGN KEY (IDPatient) REFERENCES PATIENT(ID)
);
ALTER SEQUENCE resultat_analyse_id_seq OWNED BY RESULTAT_ANALYSE.ID;

CREATE SEQUENCE observation_generale_id_seq;
CREATE TABLE OBSERVATION_GENERALE (
ID smallint PRIMARY KEY DEFAULT nextval('observation_generale_id_seq') ,
IDPatient INTEGER NOT NULL,
IDPersonnel INTEGER NOT NULL,
DateEtHeure TIMESTAMP,
Observation VARCHAR,
FOREIGN KEY (IDPatient) REFERENCES PATIENT(ID),
FOREIGN KEY (IDPersonnel) REFERENCES PERSONNEL(ID)
) ;
ALTER SEQUENCE observation_generale_id_seq OWNED BY OBSERVATION_GENERALE.ID;

CREATE SEQUENCE procedure_id_seq;
CREATE TABLE PROCEDURE (
ID smallint PRIMARY KEY DEFAULT nextval('procedure_id_seq') ,
IDPatient INTEGER  NOT NULL,
DateEtHeure TIMESTAMP,
Description VARCHAR,
FOREIGN KEY (IDPatient) REFERENCES PATIENT(ID)
) ;
ALTER SEQUENCE procedure_id_seq OWNED BY PROCEDURE.ID;

CREATE TABLE REL_PATIENT_CLIENT (
ID_Client INTEGER NOT NULL,
ID_Patient INTEGER NOT NULL,
DateDebut DATE NOT NULL,
DateFin DATE,
FOREIGN KEY (ID_Client) REFERENCES CLIENT(ID),
FOREIGN KEY (ID_Patient) REFERENCES PATIENT(ID)
);

CREATE TABLE REL_PATIENT_PERSONNEL (
ID_Personnel INTEGER NOT NULL,
ID_Patient INTEGER NOT NULL,
DateDebut DATE NOT NULL,
DateFin DATE,
FOREIGN KEY (ID_Personnel) REFERENCES PERSONNEL(ID),
FOREIGN KEY (ID_Patient) REFERENCES PATIENT(ID)
);


CREATE TABLE REL_TRAITEMENT_MEDICAMENT (
NomMolecule VARCHAR NOT NULL,
ID_Traitement INTEGER NOT NULL,
Quantite INTEGER,
FOREIGN KEY (NomMolecule) REFERENCES MEDICAMENT(NomMolecule),
FOREIGN KEY (ID_Traitement) REFERENCES TRAITEMENT(ID)
);

INSERT INTO ESPECE (Espece) VALUES ('Félins');
INSERT INTO ESPECE (Espece) VALUES ('Canidés');
INSERT INTO ESPECE (Espece) VALUES ('Reptiles');
INSERT INTO ESPECE (Espece) VALUES ('Rongeurs');
INSERT INTO ESPECE (Espece) VALUES ('Oiseaux');
INSERT INTO ESPECE (Espece) VALUES ('Autres');


INSERT INTO PATIENT (Nom, DateDeNaissance, Taille, NumeroPuceID, NumeroPasseport, Espece)
VALUES ('Oscar', '2008-08-21', 'Petite', 1, 26, 'Reptiles') ;

INSERT INTO PATIENT (Nom, DateDeNaissance, Taille, NumeroPuceID, NumeroPasseport, Espece)
VALUES ('Loulou', '2012-07-12', 'Petite', 2, 196, 'Canidés') ;

INSERT INTO PATIENT (Nom, DateDeNaissance, Taille, NumeroPuceID, NumeroPasseport, Espece)
VALUES ('Pilou', '2016-02-07', 'Moyenne', 3, 238, 'Oiseaux') ;

INSERT INTO PATIENT (Nom, DateDeNaissance, Taille, NumeroPuceID, NumeroPasseport, Espece)
VALUES ('Titie', '2009-02-07', 'Moyenne', 4, 2385435345, 'Félins') ;


INSERT INTO CLIENT (Nom, Prenom, DateDeNaissance, Adresse, NumeroTel)
VALUES ('Kerjean', 'Loïck', '2000-07-26', '30 rue de paris 60200', '0659046286') ;

INSERT INTO CLIENT (Nom, Prenom, DateDeNaissance, Adresse, NumeroTel)
VALUES ('Trupin', 'Louis', '1999-08-22', '10 rue de la liberté 02600', '0756927645') ;

INSERT INTO CLIENT (Nom, Prenom, DateDeNaissance, Adresse, NumeroTel)
VALUES ('Branly', 'Stéphane', '2000-01-27', '14 rue des Lombards 60200', '0762383812') ;



INSERT INTO PERSONNEL (Nom, Prenom, DateDeNaissance, Adresse, NumeroTel, Poste, Specialites)
VALUES ('Dupont', 'Jean', '1965-12-12', '15 rue de Paris 60200', '0657834586', 'Veto', '{"specialites": ["Félins", "Autres"]}') ;

INSERT INTO PERSONNEL (Nom, Prenom, DateDeNaissance, Adresse, NumeroTel, Poste, Specialites)
VALUES ('Watel', 'Pierre', '1982-04-14', '1 rue de la corne du Cerf 60200', '0633562312', 'Assistant', '{"specialites": ["Rongeurs"]}') ;


INSERT INTO REL_PATIENT_CLIENT (ID_Patient, ID_Client, DateDebut, DateFin) VALUES (4,3,'2010-04-25',null);
INSERT INTO REL_PATIENT_PERSONNEL (ID_Patient, ID_Personnel, DateDebut, DateFin) VALUES (4,1,'2010-05-10',null);


INSERT INTO MEDICAMENT (NomMolecule, Description, InterditPour) VALUES ('Paracétamol', 'calme les douleurs','{"interditPour": ["Rongeurs"]}') ;
INSERT INTO MEDICAMENT (NomMolecule, Description, InterditPour) VALUES ('Benzopine', 'contre les inflammations','{"interditPour": ["Oiseaux"]}') ;
INSERT INTO MEDICAMENT (NomMolecule, Description, InterditPour) VALUES ('Triplenide', 'contre les inflammations','{"interditPour": ["Reptiles"]}') ;

INSERT INTO MESURE (IDPatient, DateEtHeure, Taille, poids) VALUES (1, '2020-10-22 07:35', 12, 20 );
INSERT INTO MESURE (IDPatient, DateEtHeure, Taille, poids) VALUES (2, '2019-08-23 09:24', 45, 37 );

INSERT INTO TRAITEMENT (IDPatient, DateEtHeure, DateDebut, Duree) VALUES (1, '2020-10-22 12:12', '2020-11-01', 20);
INSERT INTO TRAITEMENT (IDPatient, DateEtHeure, DateDebut, Duree) VALUES (2, '2019-08-23 14:53', '2019-09-01', 30);
INSERT INTO TRAITEMENT (IDPatient, DateEtHeure, DateDebut, Duree) VALUES (2, '2019-08-25 17:01', '2019-10-01', 24);

INSERT INTO  RESULTAT_ANALYSE (IDPatient, DateEtHeure, Resultat) VALUES (1, '2020-10-22 20:45', 'bons');
INSERT INTO  RESULTAT_ANALYSE (IDPatient, DateEtHeure, Resultat) VALUES (2, '2019-08-23 21:01', 'moyens');

INSERT INTO OBSERVATION_GENERALE (IDPatient, IDPersonnel, DateEtHeure, Observation) VALUES (1, 1, '2020-10-22 14:03', 'rien à signaler');
INSERT INTO OBSERVATION_GENERALE (IDPatient, IDPersonnel, DateEtHeure, Observation) VALUES (2, 1, '2019-08-23 14:15', 'rien à signaler' );

INSERT INTO PROCEDURE (IDPatient, DateEtHeure, Description) VALUES (1, '2020-10-22 14:54', 'en cours' );
INSERT INTO PROCEDURE (IDPatient, DateEtHeure, Description) VALUES (2, '2019-08-23 16:34', 'en cours' );

INSERT INTO REL_TRAITEMENT_MEDICAMENT (NomMolecule, id_traitement, quantite) VALUES ('Triplenide', 1, 50);
INSERT INTO REL_TRAITEMENT_MEDICAMENT (NomMolecule, id_traitement, quantite)  VALUES ('Benzopine', 2, 10);
INSERT INTO REL_TRAITEMENT_MEDICAMENT (NomMolecule, id_traitement, quantite)  VALUES ('Benzopine', 1, 30);



CREATE VIEW STATS_MEDICAMENTS AS
SELECT MEDICAMENT.NomMolecule, SUM(REL_TRAITEMENT_MEDICAMENT.QUANTITE)  AS QUANTITE_UTILISEE
FROM
MEDICAMENT INNER JOIN REL_TRAITEMENT_MEDICAMENT
ON MEDICAMENT.NomMolecule = REL_TRAITEMENT_MEDICAMENT.NomMolecule
GROUP BY MEDICAMENT.NomMolecule;

CREATE VIEW NBR_TRAITEMENT AS
SELECT COUNT(*) AS NBR_TRAITEMENT
FROM TRAITEMENT;

CREATE VIEW NBR_PROCEDURE AS
SELECT COUNT(*) AS NBR_PROCEDURE
FROM PROCEDURE;

CREATE VIEW NBR_RESULTAT_ANALYSE AS
SELECT COUNT(*) AS NBR_RESULTAT_ANALYSE
FROM RESULTAT_ANALYSE;

CREATE VIEW NBR_MESURE AS
SELECT COUNT(*) AS NBR_MESURE
FROM MESURE;

CREATE VIEW NBR_TRAITEMENT_PAR_ESPECE AS
SELECT PATIENT.Espece, COUNT(*) AS NBR_TRAITEMENT_ESPECE
FROM TRAITEMENT INNER JOIN PATIENT 
ON PATIENT.ID = TRAITEMENT.IDPATIENT
GROUP BY PATIENT.Espece;

CREATE VIEW PROPRIETAIRE_ACTUEL AS 
SELECT PATIENT.NOM AS Nom_animal, REL_PATIENT_CLIENT.ID_Patient, REL_PATIENT_CLIENT.ID_Client, CLIENT.NOM, CLIENT.PRENOM, REL_PATIENT_CLIENT.DateDebut
FROM REL_PATIENT_CLIENT INNER JOIN CLIENT
ON REL_PATIENT_CLIENT.ID_Client = CLIENT.ID
INNER JOIN PATIENT ON REL_PATIENT_CLIENT.ID_Patient = PATIENT.ID
WHERE REL_PATIENT_CLIENT.DateFin IS NULL;


CREATE VIEW SOIGNANT_ACTUEL AS 
SELECT PATIENT.NOM AS Nom_animal, REL_PATIENT_PERSONNEL.ID_Patient, REL_PATIENT_PERSONNEL.ID_Personnel, PERSONNEL.NOM, PERSONNEL.PRENOM, REL_PATIENT_PERSONNEL.DateDebut
FROM REL_PATIENT_PERSONNEL INNER JOIN PERSONNEL
ON REL_PATIENT_PERSONNEL.ID_Personnel = PERSONNEL.ID
INNER JOIN PATIENT ON REL_PATIENT_PERSONNEL.ID_Patient = PATIENT.ID
WHERE REL_PATIENT_PERSONNEL.DateFin IS NULL;

CREATE VIEW PROPRIETAIRE_PASSE AS 
SELECT PATIENT.NOM AS Nom_animal, REL_PATIENT_CLIENT.ID_Patient, REL_PATIENT_CLIENT.ID_Client, CLIENT.NOM, CLIENT.PRENOM, REL_PATIENT_CLIENT.DateDebut, REL_PATIENT_CLIENT.DateFin
FROM REL_PATIENT_CLIENT INNER JOIN CLIENT
ON REL_PATIENT_CLIENT.ID_Client = CLIENT.ID
INNER JOIN PATIENT ON REL_PATIENT_CLIENT.ID_Patient = PATIENT.ID
WHERE REL_PATIENT_CLIENT.DateFin IS NOT NULL;


CREATE VIEW SOIGNANT_PASSE AS 
SELECT PATIENT.NOM AS Nom_animal, REL_PATIENT_PERSONNEL.ID_Patient, REL_PATIENT_PERSONNEL.ID_Personnel, PERSONNEL.NOM, PERSONNEL.PRENOM, REL_PATIENT_PERSONNEL.DateDebut, REL_PATIENT_PERSONNEL.DateFin
FROM REL_PATIENT_PERSONNEL INNER JOIN PERSONNEL
ON REL_PATIENT_PERSONNEL.ID_Personnel = PERSONNEL.ID
INNER JOIN PATIENT ON REL_PATIENT_PERSONNEL.ID_Patient = PATIENT.ID
WHERE REL_PATIENT_PERSONNEL.DateFin IS NOT NULL;

CREATE VIEW NBR_PATIENTS_EN_COURS AS
SELECT COUNT(*) AS NBR_PATIENTS_EN_COURS
FROM SOIGNANT_ACTUEL
GROUP BY ID_Patient;
